In [2]:
#Matrix multiplication
import numpy as np

A=np.arange(21,30).reshape(3,3)
B=np.arange(31,40).reshape(3,3)

A.dot(B)

array([[2250, 2316, 2382],
       [2556, 2631, 2706],
       [2862, 2946, 3030]])

In [6]:
#Properties of matrix multiplication
#ABC =  (AB)C = A(BC)
import numpy as np
A=np.arange(21,30).reshape(3,3)
B=np.arange(31,40).reshape(3,3)
C=np.arange(41,50).reshape(3,3)

temp1=(A.dot(B)).dot(C)
print("Temp1:")
print(temp1)
temp2=A.dot((B.dot(C)))
print("Temp2:")
print(temp2)

Temp1:
[[306108 313056 320004]
 [347742 355635 363528]
 [389376 398214 407052]]
Temp2:
[[306108 313056 320004]
 [347742 355635 363528]
 [389376 398214 407052]]


In [8]:
import numpy as np
#create a 4*4 matrix
arr = np.arange(100,116).reshape(4,4)
print("Array is:")
print(arr)
#find the determinant
np.linalg.det(arr)

Array is:
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]]


-2.958228394578808e-31

In [10]:
#Code for inverse in python

import numpy as np
#create an array arr1
arr1 = np.arange(5,21).reshape(4,4)
print(arr1)
#find the inverse
np.linalg.inv(arr1)

 

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


array([[-6.77233027e+13,  6.09509724e+14, -1.01584954e+15,
         4.74063119e+14],
       [-3.26200575e+15,  3.83765382e+15,  2.11070960e+15,
        -2.68635767e+15],
       [ 6.72718140e+15, -9.50383681e+15, -1.17387058e+15,
         3.95052599e+15],
       [-3.39745235e+15,  5.05667327e+15,  7.90105198e+13,
        -1.73823144e+15]])

In [2]:
import pandas as pd
import numpy as np

#you don’t need to bother about the following. It just #transforms the data from original source into matrix

Df = pd.read_csv("baseball.csv”)
Df1 = df.head(14)

# We are just taking 6 features to calculate θ.
X = Df1[[‘RS’, ‘RA’, ‘W’, ‘OBP’,'SLG','BA']]
Y=Df1['OOBP']

#Converting X to matrix
X = np.asmatrix(X)

#taking transpose of X and assigning it to x
x= np.transpose(X)

#finding multiplication
T= x.dot(X)

#inverse of T - provided it is invertible otherwise we use pseudoinverse
inv=np.linalg.inv(T)

#calculating θ
theta=(inv.dot(X.T)).dot(Y)

SyntaxError: EOL while scanning string literal (<ipython-input-2-8c07e3ef5a8d>, line 6)