In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("train.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
sex=pd.get_dummies(df['Sex'])
embark=pd.get_dummies(df['Embarked'])

In [5]:
embark

C  Q  S
0    0  0  1
1    1  0  0
2    0  0  1
3    0  0  1
4    0  0  1
..  .. .. ..
886  0  0  1
887  0  0  1
888  0  0  1
889  1  0  0
890  0  1  0

[891 rows x 3 columns]

In [6]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [7]:
a=df['Age'].mean()
df['Age'].fillna(a, inplace=True)

In [8]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.000000      1   
2                               Heikkinen, Miss. Laina    0  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.000000      1   
4                             Allen, Mr. William Henry    1  35.000000      0   
..                                                 ...  ...        ...    ...   
886                              Montvila, Rev. Juozas    1  27.000000      0   
887                       Graham, Miss. Margaret Edith    0  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"    0  29.699118      1   
889                              Behr, Mr. Karl Howell    1  26.000000      0   
890                                Dooley, Mr. Patrick    1  32.000000      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [9]:
titanic_clean=pd.concat([df,sex,embark],axis=1)
titanic_clean

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.000000      1   
2                               Heikkinen, Miss. Laina    0  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.000000      1   
4                             Allen, Mr. William Henry    1  35.000000      0   
..                                                 ...  ...        ...    ...   
886                              Montvila, Rev. Juozas    1  27.000000      0   
887                       Graham, Miss. Margaret Edith    0  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"    0  29.699118      1   
889                              Behr, Mr. Karl Howell    1  26.000000      0   
890                                Dooley, Mr. Patrick    1  32.000000      0   

     Parch            Ticket     Fare Cabin Embarked  0  1  C  Q  S  
0        0         A/5 21171   7.2500   NaN        S  0  1  0  0  1  
1        0          PC 17599  71.2833   C85        C  1  0  1  0  0  
2        0  STON/O2. 3101282   7.9250   NaN        S  1  0  0  0  1  
3        0            113803  53.1000  C123        S  1  0  0  0  1  
4        0            373450   8.0500   NaN        S  0  1  0  0  1  
..     ...               ...      ...   ...      ... .. .. .. .. ..  
886      0            211536  13.0000   NaN        S  0  1  0  0  1  
887      0            112053  30.0000   B42        S  1  0  0  0  1  
888      2        W./C. 6607  23.4500   NaN        S  1  0  0  0  1  
889      0            111369  30.0000  C148        C  0  1  1  0  0  
890      0            370376   7.7500   NaN        Q  0  1  0  1  0  

[891 rows x 17 columns]

In [26]:
titanic_clean.rename(columns={1:"female",0:"male"})

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name        Age  SibSp  \
0                              Braund, Mr. Owen Harris  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.000000      1   
2                               Heikkinen, Miss. Laina  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.000000      1   
4                             Allen, Mr. William Henry  35.000000      0   
..                                                 ...        ...    ...   
886                              Montvila, Rev. Juozas  27.000000      0   
887                       Graham, Miss. Margaret Edith  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"  29.699118      1   
889                              Behr, Mr. Karl Howell  26.000000      0   
890                                Dooley, Mr. Patrick  32.000000      0   

     Parch            Ticket     Fare Cabin  male  female  C  Q  S  
0        0         A/5 21171   7.2500   NaN     0       1  0  0  1  
1        0          PC 17599  71.2833   C85     1       0  1  0  0  
2        0  STON/O2. 3101282   7.9250   NaN     1       0  0  0  1  
3        0            113803  53.1000  C123     1       0  0  0  1  
4        0            373450   8.0500   NaN     0       1  0  0  1  
..     ...               ...      ...   ...   ...     ... .. .. ..  
886      0            211536  13.0000   NaN     0       1  0  0  1  
887      0            112053  30.0000   B42     1       0  0  0  1  
888      2        W./C. 6607  23.4500   NaN     1       0  0  0  1  
889      0            111369  30.0000  C148     0       1  1  0  0  
890      0            370376   7.7500   NaN     0       1  0  1  0  

[891 rows x 15 columns]

In [10]:
titanic_clean.drop(['Sex','Embarked'],axis=1,inplace=True)

In [17]:
titanic_clean

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name        Age  SibSp  \
0                              Braund, Mr. Owen Harris  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.000000      1   
2                               Heikkinen, Miss. Laina  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.000000      1   
4                             Allen, Mr. William Henry  35.000000      0   
..                                                 ...        ...    ...   
886                              Montvila, Rev. Juozas  27.000000      0   
887                       Graham, Miss. Margaret Edith  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"  29.699118      1   
889                              Behr, Mr. Karl Howell  26.000000      0   
890                                Dooley, Mr. Patrick  32.000000      0   

     Parch            Ticket     Fare Cabin  0  1  C  Q  S  
0        0         A/5 21171   7.2500   NaN  0  1  0  0  1  
1        0          PC 17599  71.2833   C85  1  0  1  0  0  
2        0  STON/O2. 3101282   7.9250   NaN  1  0  0  0  1  
3        0            113803  53.1000  C123  1  0  0  0  1  
4        0            373450   8.0500   NaN  0  1  0  0  1  
..     ...               ...      ...   ... .. .. .. .. ..  
886      0            211536  13.0000   NaN  0  1  0  0  1  
887      0            112053  30.0000   B42  1  0  0  0  1  
888      2        W./C. 6607  23.4500   NaN  1  0  0  0  1  
889      0            111369  30.0000  C148  0  1  1  0  0  
890      0            370376   7.7500   NaN  0  1  0  1  0  

[891 rows x 15 columns]

In [31]:
#logistic Regresion
x= titanic_clean[['Age','Pclass',0,1,'S','Q','C']]
y= titanic_clean['Survived']

In [37]:
from sklearn import datasets
from sklearn import linear_model
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=101)


In [47]:
from sklearn.linear_model import LogisticRegression

model_log = LogisticRegression()
model_log.fit(x_train,y_train)

y_pred=model_log.predict(x_test)
print("Test score:{:.6f}".format(np.mean(y_pred==y_test)))

C:\Users\DELL\Desktop\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Test score:0.798883


In [51]:
from sklearn import metrics
print("\n","Expected prediction  accuracy:",metrics.accuracy_score(y_test,y_pred))


 Expected prediction  accuracy: 0.7988826815642458


In [63]:

model_log.fit(x_train,y_train)

y_pred_proba=model_log.predict_proba(x_test)
print(y_pred[0:5])
print(y_pred_proba[0:5])
#print("Test score:{:.6f}".format(np.mean(y_pred==y_test)))

[0 1 0 0 0]
[[0.68641963 0.31358037]
 [0.05280986 0.94719014]
 [0.51913507 0.48086493]
 [0.85510147 0.14489853]
 [0.79973644 0.20026356]]


C:\Users\DELL\Desktop\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [64]:
x.head(5)

Age  Pclass  0  1  S  Q  C
0  22.0       3  0  1  1  0  0
1  38.0       1  1  0  0  0  1
2  26.0       3  1  0  1  0  0
3  35.0       1  1  0  1  0  0
4  35.0       3  0  1  1  0  0

In [77]:
X=pd.read_csv("new_model3.csv")
X

Age  Pclass  0  1  S  Q  C
0   30       1  1  0  1  0  0
1   30       1  1  0  0  1  0
2   30       1  1  0  0  0  1

In [70]:
odel_log = LogisticRegression()
model_log.fit(x_train,y_train)
x_test=pd.read_csv("new_model.csv")
y_pred_proba=model_log.predict_proba(x_test)
print(y_pred[0:5])
print(y_pred_proba[0:5])

[0 1 0 0 0]
[[0.91799093 0.08200907]
 [0.09112475 0.90887525]
 [0.68555043 0.31444957]]


C:\Users\DELL\Desktop\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [74]:
odel_log = LogisticRegression()
model_log.fit(x_train,y_train)
x_test=pd.read_csv("new_model1.csv")
y_pred_proba=model_log.predict_proba(x_test)
print(y_pred[0:5])
print(y_pred_proba[0:5])

[0 1 0 0 0]
[[0.11242727 0.88757273]
 [0.59145644 0.40854356]]


C:\Users\DELL\Desktop\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [76]:
model_log = LogisticRegression()
model_log.fit(x_train,y_train)
x_test=pd.read_csv("new_model2.csv")
y_pred_proba=model_log.predict_proba(x_test)
print(y_pred[0:5])
print(y_pred_proba[0:5])

[0 1 0 0 0]
[[0.11242727 0.88757273]
 [0.26047527 0.73952473]
 [0.49479626 0.50520374]]


C:\Users\DELL\Desktop\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [78]:
model_log = LogisticRegression()
model_log.fit(x_train,y_train)
x_test=pd.read_csv("new_model3.csv")
y_pred_proba=model_log.predict_proba(x_test)
print(y_pred[0:5])
print(y_pred_proba[0:5])

[0 1 0 0 0]
[[0.11242727 0.88757273]
 [0.08609418 0.91390582]
 [0.07131146 0.92868854]]


C:\Users\DELL\Desktop\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [80]:
from sklearn import datasets
from sklearn import linear_model
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=101)
from sklearn.linear_model import LogisticRegression

model_log = LogisticRegression()
model_log.fit(x_train,y_train)

y_pred=model_log.predict(x_test)
print("Test score:{:.6f}".format(np.mean(y_pred==y_test)))

Test score:0.798883


C:\Users\DELL\Desktop\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [83]:
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_test,y_pred)
print(confusion_matrix)

[[87 12]
 [24 56]]


In [85]:
a=(87+12+24+56)
b=(87+56)
print(b/a)

0.7988826815642458
