In [2]:
import numpy as np
a=np.array([4,8,0,2,1,6])
b=np.array([5,2,9,4])
a=a.reshape(3,2)
b=b.reshape(2,2)
print(a)
print(b)
print(a.dot(b))
#print(b.dot(a))

[[4 8]
 [0 2]
 [1 6]]
[[5 2]
 [9 4]]
[[92 40]
 [18  8]
 [59 26]]


ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [5]:
import numpy as np
a=np.array([2,5,1,7,3,6])
b=np.array([1,8,9,4,3,5])
a=a.reshape(2,3)
b=b.reshape(3,2)
print("Matrix A")
print(a)
print("Matrix B")
print(b)
print("Multiplication: A*B")
print(a.dot(b))
print("Multiplication: B*A")
print(b.dot(a))


Matrix A
[[2 5 1]
 [7 3 6]]
Matrix B
[[1 8]
 [9 4]
 [3 5]]
Multiplication: A*B
[[50 41]
 [52 98]]
Multiplication: B*A
[[58 29 49]
 [46 57 33]
 [41 30 33]]


In [1]:
import numpy as np
import pandas as pd
a=np.array([1,2,3,4])
b=np.array([0.66,-5,0.2,100])
a=a.reshape(2,2)
b=b.reshape(2,2)
print(a)
print(b)
print(a+b)
print(a-b)
print(5*a)

[[1 2]
 [3 4]]
[[  0.66  -5.  ]
 [  0.2  100.  ]]
[[  1.66  -3.  ]
 [  3.2  104.  ]]
[[  0.34   7.  ]
 [  2.8  -96.  ]]
[[ 5 10]
 [15 20]]


In [3]:
#Inverse of a matrix
from numpy.linalg import inv
a=np.array([[1.,2.],[3.,4.]])
print(a)
ainv=inv(np.matrix(a))
print(ainv)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [4]:
print(a.dot(ainv))

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


#Inverse of a matrix
from numpy.linalg import inv
a=np.array([[1,2],[3,4]])
print(a)
ainv=inv(np.matrix(a))
print(ainv)

print(a.dot(ainv))

In [8]:
#Solving a set of simultaneous equation
#7x+2y+z=21
#3y-z=5
#-3x+4y-2z=-1
import numpy as np
a=np.array([7,2,1,0,3,-1,-3,4,-2])
b=np.array([21,5,-1])
a=a.reshape(3,3)
#AX=B
#X=A inverse * B
ainv=inv(np.matrix(a))
print(ainv)
x=ainv.dot(b)
x


[[ -2.   8.  -5.]
 [  3. -11.   7.]
 [  9. -34.  21.]]


matrix([[ 3.,  1., -2.]])

In [9]:
import numpy as np
a=np.array([1,1,-1,8,3,-6,-4,-1,3])
b=np.array([1,1,1])
a=a.reshape(3,3)
#AX=B
#X=A inverse * B
ainv=inv(np.matrix(a))
print(ainv)
x=ainv.dot(b)
x


[[-3.  2.  3.]
 [ 0.  1.  2.]
 [-4.  3.  5.]]


matrix([[2., 3., 4.]])

In [11]:
import numpy as np
a=np.array([1,1,-1,1,-2,3,2,3,1])
b=np.array([4,-6,7])
a=a.reshape(3,3)
print(a)
#AX=B
#X=A inverse * B
ainv=inv(np.matrix(a))
print(ainv)
x=ainv.dot(b)
x


[[ 1  1 -1]
 [ 1 -2  3]
 [ 2  3  1]]
[[ 0.84615385  0.30769231 -0.07692308]
 [-0.38461538 -0.23076923  0.30769231]
 [-0.53846154  0.07692308  0.23076923]]


matrix([[ 1.,  2., -1.]])