In [12]:
import numpy as np
a=np.array([1,2,3],dtype='float64')
print(a)
print(a.dtype)
print(type(a))
b=np.array([[1.1,2],[3,4]],dtype='int64')
print(b)
print(b.dtype)
print(b.size)
print(b.ndim)#no. of dimenssion

print(np.linspace(0,2,9))

[1. 2. 3.]
float64
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
int64
4
2
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [13]:
#Initial place holders
a=np.zeros(5)#default data type is float
a1=np.ones(5)#to create array of ones
a2=np.ones((3,2)) #create 2 dimensionl array
print(a)
print(a1)
print(a2)


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
a3=np.full((3,3),8)
a3

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [17]:
print(np.eye(3))#Identity matrix of 0,1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
a=np.arange(0,24,1,dtype=int)#start stop step
a
a=np.arange(24,0,-1,dtype=int)#start stop step
a
a=np.arange(0,24,3,dtype=int)#start stop step
a
a=np.arange(-15,0,1.5,dtype=int)#start stop step
a
a=np.arange(0,24,1.5,dtype=float)#start stop step
a
a=np.arange(0,24,2.5,dtype=int)#start stop step
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
b=a.reshape(2,4,3)#make 2 matrix of 4 by 3
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [22]:
print(5*np.eye(3))


[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


In [31]:
#array aggregate functions
import numpy as np
b=np.array([[1,2,3,40],[5,6,7,8],[9,10,11,12]])
print(b)
print(b.max())
print(b.max(axis=0))
print(b.max(axis=1))

[[ 1  2  3 40]
 [ 5  6  7  8]
 [ 9 10 11 12]]
40
[ 9 10 11 40]
[40  8 12]


In [32]:
print(b.min())

1


In [33]:
print(b.sum(axis=0))#columnwise sum

[15 18 21 60]


In [34]:
print(b.sum(axis=1))# row wise sum

[46 26 42]


In [35]:
print(b.mean())

9.5


In [36]:
print(b.mean(axis=0))

[ 5.  6.  7. 20.]


In [37]:
print(b.sum())#summation of all elements

114


In [45]:
#array mathd
a=np.array([1,2,3],float)
b=np.array([5,2,6],float)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a*a)
print(a**2)
print(a**3)
print(a**0.5)#square root

[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[0.2 1.  0.5]
[1. 4. 9.]
[1. 4. 9.]
[ 1.  8. 27.]
[1.         1.41421356 1.73205081]


In [51]:
#Array sub setting and slicing
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print("--------------------------------------------------------------
print("first row")
print(a[0,]) #first row
print("--------------------------------------------------------------
print(a[0:2,])# first two rows all column
print("--------------------------------------------------------------
print(a[1:3,])#2nd and 3rd row all columns
print("--------------------------------------------------------------

print(a[0:2,0])#Row 1 and 2, column 1
print(a[0,1:3])#first 2 rows and col 2 and 3
print(a[:,1:3])#all rows and col 2&3

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
first row
[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[1 5]
[2 3]
[[ 2  3]
 [ 6  7]
 [10 11]]
