In [1]:
myString <- "Hello, World!"

In [2]:
print ( myString)

[1] "Hello, World!"


In [3]:
myString <- "Hello, World!"

print ( myString)

[1] "Hello, World!"


Comment

In [5]:
# My first program in R Programming

R does not support multi-line comments but you can perform a trick which is something as follows −

In [7]:
if(FALSE) {
   "This is a demo for multi-line comments and it should be put inside either a 
      single OR double quote"
}

myString <- "Hello, World!"
print ( myString)

[1] "Hello, World!"


In [8]:
v <- TRUE 
print(class(v))

[1] "logical"


In [9]:
v <- 12 
print(class(v))

[1] "numeric"


In [10]:
v <- 12.50 
print(class(v))

[1] "numeric"


In [11]:
v <- 12L
print(class(v))

[1] "integer"


In [12]:
v <- 3 + 2i 
print(class(v))

[1] "complex"


In [13]:
v <- "TRUE" 
print(class(v))

[1] "character"


In [14]:
v <- charToRaw("Hello")
print(class(v))

[1] "raw"


Vectors

In [15]:
# Create a vector.
apple <- c('red','green',"yellow")
print(apple)

# Get the class of the vector.
print(class(apple))

[1] "red"    "green"  "yellow"
[1] "character"


Lists

In [16]:
# Create a list.
list1 <- list(c(2,5,3),21.3,sin)

# Print the list.
print(list1)

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
function (x)  .Primitive("sin")



Matrices

In [17]:
# Create a matrix.
M = matrix( c('a','a','b','c','b','a'), nrow = 2, ncol = 3, byrow = TRUE)
print(M)

     [,1] [,2] [,3]
[1,] "a"  "a"  "b" 
[2,] "c"  "b"  "a" 


Arrays

In [18]:
# Create an array.
a <- array(c('green','yellow'),dim = c(3,3,2))
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"



In [20]:
# Create an array.
a <- array(c('green','yellow'),dim = c(2,3,1))
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "green"  "green" 
[2,] "yellow" "yellow" "yellow"



Factors


In [21]:
# Create a vector.
apple_colors <- c('green','green','yellow','red','red','red','green')

# Create a factor object.
factor_apple <- factor(apple_colors)

# Print the factor.
print(factor_apple)
print(nlevels(factor_apple))

[1] green  green  yellow red    red    red    green 
Levels: green red yellow
[1] 3


Data Frames

In [22]:
# Create the data frame.
BMI <- 	data.frame(
   gender = c("Male", "Male","Female"), 
   height = c(152, 171.5, 165), 
   weight = c(81,93, 78),
   Age = c(42,38,26)
)
print(BMI)

  gender height weight Age
1   Male  152.0     81  42
2   Male  171.5     93  38
3 Female  165.0     78  26


In [25]:
# Create the data frame.
BMI <- 	data.frame(
   gender = c("Male", "Male","Female"), 
   height = c(152, 171.5, 165), 
   weight = c(81,93, 78),
   Age = c(42,38,1)
)
print(BMI)

  gender height weight Age
1   Male  152.0     81  42
2   Male  171.5     93  38
3 Female  165.0     78   1


Variable Assignment

In [26]:
# Assignment using equal operator.
var.1 = c(0,1,2,3)           

# Assignment using leftward operator.
var.2 <- c("learn","R")   

# Assignment using rightward operator.   
c(TRUE,1) -> var.3           

print(var.1)
cat ("var.1 is ", var.1 ,"\n")
cat ("var.2 is ", var.2 ,"\n")
cat ("var.3 is ", var.3 ,"\n")

[1] 0 1 2 3
var.1 is  0 1 2 3 
var.2 is  learn R 
var.3 is  1 1 


Data Type of a Variable

In [27]:
var_x <- "Hello"
cat("The class of var_x is ",class(var_x),"\n")

var_x <- 34.5
cat("  Now the class of var_x is ",class(var_x),"\n")

var_x <- 27L
cat("   Next the class of var_x becomes ",class(var_x),"\n")

The class of var_x is  character 
  Now the class of var_x is  numeric 
   Next the class of var_x becomes  integer 


Finding Variables
To know all the variables currently available in the workspace we use the ls() function. Also the ls() function can use patterns to match the variable names.

In [28]:
print(ls())

 [1] "a"            "apple"        "apple_colors" "BMI"          "factor_apple"
 [6] "list1"        "M"            "myString"     "v"            "var.1"       
[11] "var.2"        "var.3"        "var_x"       


In [29]:
# List the variables starting with the pattern "var".
print(ls(pattern = "var"))   

[1] "var.1" "var.2" "var.3" "var_x"


In [30]:
print(ls(all.name = TRUE))

 [1] ".pbd_env"     "a"            "apple"        "apple_colors" "BMI"         
 [6] "factor_apple" "list1"        "M"            "myString"     "v"           
[11] "var.1"        "var.2"        "var.3"        "var_x"       


Deleting Variables
Variables can be deleted by using the rm() function.

In [31]:
rm(var.3)
print(var.3)

ERROR: Error in print(var.3): object 'var.3' not found


All the variables can be deleted by using the rm() and ls() function together.

In [32]:
rm(list = ls())
print(ls())

character(0)
